spring.application.name=TRANSACTION-SERVICE
server.port=8086


# Connection With MongoDb Server

spring.data.mongodb.uri=mongodb://localhost:27017/transaction-service

# Connection With Kafka Server
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=group-1
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
